kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: izcKUKXGlZyWjXLQI9ZijkFVtLWi2cXSCHsvDPZFeVY=
      - identity: {}
